name: Deploy Telegram Bot

on:
  push:
    branches:
      - main  # 或您选择的分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'   # 使用可用的 Python 3.8.x 版本
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: 运行机器人
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_USERNAME: ${{ secrets.TELEGRAM_USERNAME }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        run: python main.py
